name: Rust

on: [push]

jobs:
  linux-x86_64:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - run: cargo build --all-features --release && mkdir -p rstun-linux-x86_64
                                                  && mv target/release/rstunc ./rstun-linux-x86_64/
                                                  && mv target/release/rstund ./rstun-linux-x86_64/
                                                  && tar zcf rstun-linux-x86_64.tar.gz ./rstun-linux-x86_64/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rstun-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  windows-x86_64:
    name: Windows x86_64
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      - run: cargo build --all-features --release && mkdir -p rstun-windows-x86_64
                                                  && mv target/release/rstunc.exe ./rstun-windows-x86_64/
                                                  && mv target/release/rstund.exe ./rstun-windows-x86_64/
                                                  && 7z a rstun-windows-x86_64.zip ./rstun-windows-x86_64/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rstun-windows-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

